parameter1/cox-matthews-associates-websites

sites/diverseeducation.com/server/graphql/fragments/champion-promotion.js
sites/diverseeducation.com/server/routes/awards.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/champions.marko

should lay out as follows
- Leaderboard
- Header & teaser block
- website-option-content(single promotion displaying body field)
- two gray cards(Deadline|About)
- latest content scheduled to section(exclude promos & pull up to 100 pieces)

Champions page

---

packages/global/components/blocks/premium-employers.marko
packages/global/scss/components/blocks/_premium-employers.scss
sites/ccnewsnow.com/server/templates/content/index.marko
sites/ccnewsnow.com/server/templates/index.marko
sites/ccnewsnow.com/server/templates/website-section/index.marko
sites/diverseeducation.com/server/templates/content/index.marko
sites/diverseeducation.com/server/templates/index.marko
sites/diverseeducation.com/server/templates/website-section/index.marko
sites/diversemilitary.net/server/templates/content/index.marko
sites/diversemilitary.net/server/templates/index.marko
sites/diversemilitary.net/server/templates/website-section/index.marko
sites/divhealth.net/server/templates/content/index.marko
sites/divhealth.net/server/templates/index.marko
sites/divhealth.net/server/templates/website-section/index.marko

Replace ad above this block and made the premium employer block break out of the page container with the gray background.

Update display of Premium Employers block

---

packages/global/components/blocks/esurveypro.marko
packages/global/scss/components/blocks/_esurveypro.scss

Add flush-x and add !important style overrides for eSurvey poll block

Add styles to override included style tag from esurvey

---

packages/global/components/blocks/magazine-issue-cards.marko
packages/global/components/blocks/magazine-publications.marko
packages/global/components/blocks/marko.json
packages/global/components/flows/magazine-issue-archive.marko
packages/global/components/flows/magazine-latest-issue.marko
packages/global/components/flows/marko.json
packages/global/components/nodes/magazine-issue-archive.marko
packages/global/components/nodes/magazine-latest-issue.marko
packages/global/components/nodes/marko.json
packages/global/components/query-total-count.marko
packages/global/graphql/fragments/magazine-issue-archive.js
packages/global/graphql/fragments/magazine-issue-page.js
packages/global/graphql/fragments/magazine-latest-issue.js
packages/global/graphql/fragments/magazine-publication-list.js
packages/global/graphql/fragments/magazine-publication-page.js
packages/global/routes/index.js
packages/global/routes/magazine.js
packages/global/scss/components/_magazine.scss
packages/global/scss/core.scss
packages/global/templates/magazine/index.marko
packages/global/templates/magazine/issue.marko
packages/global/templates/magazine/publication.marko

I left the home page as is, but when you want to add this to the home page you will need the following:
```
import latestIssueFragment from "@cox-matthews-associates/package-global/graphql/fragments/magazine-latest-issue";
<div class="col-lg-4 mb-block">
<marko-web-query|{ node: issue }|
name="magazine-latest-issue"
params={ publicationId: "61128276dc429e5a098b4576", queryFragment: latestIssueFragment, requiresImage: true  }
>
<global-magazine-latest-issue-flow issue-node=issue>
<@header>
<marko-web-magazine-issue-name tag=null obj=issue link=true>
In Print
</marko-web-magazine-issue-name>
</@header>
</global-magazine-latest-issue-flow>
</marko-web-query>
</div>
```

Add Magazine landing pages(magazine|publication|issue) & homepage block.  

---

packages/global/components/blocks/marko.json
packages/global/components/blocks/section-feed.marko
packages/global/components/layouts/content/default.marko
packages/global/components/layouts/website-section/marko.json
packages/global/components/layouts/website-section/upcoming-archive-feed.marko
packages/global/components/nodes/section-feed-content.marko
packages/global/graphql/fragments/section-feed-block.js
packages/global/scss/components/_content-page.scss
packages/global/scss/components/blocks/_section-feed.scss
sites/diverseeducation.com/server/routes/website-section.js
sites/diverseeducation.com/server/templates/website-section/webinars.marko

https://trello.com/c/wj4kLAlC/80-webcasts
At the moment I have it pulling all published webinars sorted by start date.  This would naturally pull upcoming/future webinars to the top of the list and switch the button text between `View Webinar` & `Register for Webinar`.  The would eliminate the need for upcoming vs archived.

Add support for query all website scheduled content sorted by startDate Desc, specifically for /webinars & event/diverse-live-talk.

---

packages/global/components/document.marko
packages/global/components/marko.json
packages/global/components/site-header-2.marko
packages/global/scss/_variables.scss
packages/global/scss/components/_site-navbar.scss
packages/global/scss/components/_site-navbar2.scss
packages/global/scss/core.scss
sites/ccnewsnow.com/config/navigation.js
sites/ccnewsnow.com/config/subscribe.js
sites/ccnewsnow.com/server/styles/index.scss
sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/config/subscribe.js
sites/diverseeducation.com/server/styles/index.scss
sites/diversemilitary.net/config/navigation.js
sites/diversemilitary.net/config/subscribe.js
sites/diversemilitary.net/server/styles/index.scss
sites/divhealth.net/config/navigation.js
sites/divhealth.net/config/subscribe.js
sites/divhealth.net/server/styles/index.scss

This can be turned on for any of the sites.  In navigation.js config you will need to set type: 'sitenav2' & withing the site's index.js the following should be set:
```
$theme-site-header-breakpoints: (
hide-primary: 1200px, // effectively always hide the primary nav
hide-secondary: 700px,
small-logo: 775px,
small-text-primary: 0,
small-text-secondary: 830px
);
$navbarStyle: "navbar2";
```
The $navebarStyel & hide-priamary will need to be set/udated

Create new site header/navbar

---

sites/diverseeducation.com/server/templates/website-section/john-hope-franklin.marko

Remove ‘Register Now…’ button on John Hope Franklin page

---

packages/global/components/layouts/website-section/marko.json
packages/global/components/layouts/website-section/podcast-feed.marko
packages/global/graphql/fragments/website-section-with-logo-page.js
packages/global/scss/components/_podcasts-page.scss
packages/global/scss/variables/_typography.scss
sites/diverseeducation.com/server/routes/website-section.js
sites/diverseeducation.com/server/templates/website-section/podcasts.marko

This is part of a two phase update to the page.  For now it will be a full width title, logo & description with a feed of 10 podcast per page.  There will be a submit a Podcast form in the right 1/3 once setup.

Update Podcast landing page with new layout and section logo support.

---

packages/global/scss/components/_podcasts-page.scss

Adjust image CSS for mobile view on podcast page

---

packages/global/components/layouts/content/default.marko

block for ‘On the Move’ section

Add ‘Submit your professional appointment’ button to content-body

---

sites/diverseeducation.com/server/templates/static-pages/mppwsa-2021.marko
sites/diverseeducation.com/server/templates/static-pages/mppwsa.marko

Add title above logos for current year and last year’s MPPWSA pages

---

packages/global/components/blocks/premium-employers.marko

Some of these were returning without a primaryImage and displaying an "empty slot"

Require image for premium-employers block.

---

packages/global/components/blocks/premium-employers.marko

This will now allow each site to individually schedule to that block

Remove site-id from Premium Employers block

---

packages/global/browser/index.js
packages/global/browser/premium-employers.vue
packages/global/browser/ssr.js
packages/global/components/blocks/premium-employers.marko
packages/global/package.json
packages/global/scss/components/blocks/_premium-employers.scss
yarn.lock

You vue-slick-carousel like we did for premium partners to create the new premium empoyers slider.  Below is examples when there is more than 4 and 4 or less.

Add premium employers slider

---

packages/global/components/layouts/website-section/podcast-feed.marko
packages/global/scss/components/_podcasts-page.scss

Use CSS styling over RegEx in order to correct sizing of Podcast page video

---

packages/global/components/layouts/content/default.marko

Only fire ads when the overlay is not displayed.

Add !showOverlay check to ads calls

---

docker-compose.yml
packages/global/components/document.marko
packages/global/components/site-menu/index.marko
packages/global/config/identity-x-nav.js
packages/global/scss/core.scss
packages/global/start-server.js
sites/ccnewsnow.com/config/navigation.js
sites/ccnewsnow.com/config/site.js
sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/config/site.js
sites/diversemilitary.net/config/navigation.js
sites/diversemilitary.net/config/site.js
sites/divhealth.net/config/navigation.js
sites/divhealth.net/config/site.js

Add the ability to set the idxNavItems.enable prop based on IDX_NAV_ENABLE env prop.  when set to true the Account section is added to the expanded nav and mobile menu.

Add env/config based identity x user navigation

---

sites/diverseeducation.com/server/components/blocks/marko.json
sites/diverseeducation.com/server/components/blocks/promo-card-rotation.marko
sites/diverseeducation.com/server/templates/index.marko

Update Promo blocks 

---

packages/global/scss/core.scss

Privacy policy still is underlined when hovered on

Remove text-decoration on  a:hover

---

packages/global/scss/core.scss

Adjust margin-right scss to keep social icons on 1 line

---

packages/global/components/blocks/suggested-video.marko
packages/global/components/layouts/website-section/feed.marko
packages/global/scss/components/_ads.scss

update props and allow for it to span full width within the rail.  It will also auto play unmuted. :( 
@todo figure out how to hide related videos at the end.

Adjust suggested video embed prop, styles & playback

---

packages/global/components/blocks/suggested-video.marko

This fixes the issue in which the video doesn't auto-play in addition actually respecting it being muted as well

Ensure mute parameter is a number only

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Adjust years to 2024 for current and 2023 for start of past, Arthur Ashe page

---

sites/diverseeducation.com/server/components/blocks/promo-card-rotation.marko

Remove hard set ‘Sponsored’ title on promo cards

---

sites/diverseeducation.com/server/components/blocks/latest-podcast.marko
sites/diverseeducation.com/server/styles/index.scss

Additional additional styling adjustments for homepage Podcast blocks

---

packages/global/templates/content/advertising-post.marko
packages/global/templates/content/native-x-story.marko

Causes "open in new tab" to fail

Disable outbound link tracking
