sites/ccnewsnow.com/config/navigation.js
sites/ccnewsnow.com/server/templates/index.marko
sites/diversemilitary.net/config/navigation.js
sites/diversemilitary.net/server/templates/index.marko
sites/divhealth.net/config/navigation.js
sites/divhealth.net/server/templates/index.marko

Update navigation & home page blocks

---

sites/ccnewsnow.com/config/navigation.js
sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/server/templates/index.marko
sites/diversemilitary.net/config/navigation.js
sites/divhealth.net/config/navigation.js

Add Opinion block to home page

---

packages/global/components/layouts/content/default-rail.marko
packages/global/components/layouts/content/default.marko
packages/global/components/layouts/content/full-width.marko
packages/global/scss/components/_page-wrapper.scss

Remove invalid ; from code & minor css changes

---

packages/global/components/blocks/esurveypro.marko
packages/global/components/blocks/marko.json
packages/global/scss/components/blocks/_esurveypro.scss
packages/global/scss/core.scss
sites/diverseeducation.com/server/templates/content/index.marko
sites/diverseeducation.com/server/templates/index.marko
sites/diverseeducation.com/server/templates/website-section/index.marko

Add eSurveyPro block

---

packages/global/components/layouts/content/default.marko

Add social sharing to top of content page

---

sites/diverseeducation.com/config/site.js

Add youtube and instagram links

---

packages/global/redirect-handler.js
sites/diverseeducation.com/server/routes/awards.js
sites/diverseeducation.com/server/routes/awards/redirects.js

Some Examples:
- ashe => awards-honors/arthur-ashe
- 2020-arthur-ashe-jr-winners => awards-honors/arthur-ashe/2020
- article/category/emerging-scholars/?zyear=2010&Submit.x=35&Submit.y=13# => /awards-honors/emerging-scholars/2010

Add /award-honors child section redirects

---

packages/global/scss/core.scss

Update social follow header line height for menu

---

docker-compose.yml
packages/global/browser/index.js
packages/global/package.json
packages/global/routes/index.js
packages/global/routes/search.js
packages/global/scss/components/_pagination-controls.scss
packages/global/scss/components/_search-page.scss
packages/global/scss/core.scss
packages/global/start-server.js
packages/global/templates/search.marko
sites/ccnewsnow.com/config/search.js
sites/ccnewsnow.com/config/site.js
sites/diverseeducation.com/config/search.js
sites/diverseeducation.com/config/site.js
sites/diversemilitary.net/config/search.js
sites/diversemilitary.net/config/site.js
sites/divhealth.net/config/search.js
sites/divhealth.net/config/site.js
yarn.lock

Add search support

---

packages/global/components/layouts/content/default.marko
packages/global/templates/content/contact.marko
yarn.lock

Set displayPrimaryImage = false, remove lower blocks from contact template

---

packages/global/components/site-menu/components/social-icons.marko
packages/global/components/site-menu/index.marko
packages/global/components/social-follow.marko
sites/diverseeducation.com/config/navigation.js

Add awards to menu

---

packages/global/components/blocks/featured-jobs-list.marko
packages/global/components/flows/content/list.marko
packages/global/components/flows/content/marko.json
packages/global/scss/components/blocks/_featured-jobs.scss
packages/global/scss/components/blocks/_section-list.scss
packages/global/scss/core.scss

**CCN (and any other site that doesn't currently have jobs scheduled):**
**Diverse Education:**

Featured jobs per site

---

sites/ccnewsnow.com/config/navigation.js

Add additional sites

---

sites/ccnewsnow.com/server/templates/content/index.marko
sites/ccnewsnow.com/server/templates/index.marko
sites/ccnewsnow.com/server/templates/website-section/index.marko
sites/diversemilitary.net/server/templates/content/index.marko
sites/diversemilitary.net/server/templates/index.marko
sites/diversemilitary.net/server/templates/website-section/index.marko
sites/divhealth.net/server/templates/content/index.marko
sites/divhealth.net/server/templates/index.marko
sites/divhealth.net/server/templates/website-section/index.marko

Remove "Poll" and "twitter feed" blocks from military, health, ccnews

---

sites/ccnewsnow.com/config/site.js
sites/divhealth.net/config/site.js

Add facebook social link to ccnews and divhealth

---

sites/ccnewsnow.com/config/navigation.js
sites/ccnewsnow.com/server/templates/content/index.marko
sites/ccnewsnow.com/server/templates/index.marko
sites/ccnewsnow.com/server/templates/website-section/index.marko
sites/diversemilitary.net/config/navigation.js
sites/divhealth.net/config/navigation.js

Update job links

---

sites/ccnewsnow.com/config/navigation.js
sites/diversemilitary.net/config/navigation.js
sites/divhealth.net/config/navigation.js

Update ‘education’ to ‘diverse’ in menu

---

sites/ccnewsnow.com/config/navigation.js
sites/diverseeducation.com/config/navigation.js
sites/diversemilitary.net/config/navigation.js
sites/divhealth.net/config/navigation.js

Add "keep it real" link under resources and in footer

---

packages/global/components/blocks/esurveypro.marko
sites/diverseeducation.com/server/routes/diverse-poll.js
sites/diverseeducation.com/server/routes/index.js
sites/diverseeducation.com/server/templates/static-pages/diverse-poll.marko

Add diverse poll landing page

---

packages/global/scss/components/blocks/_esurveypro.scss

Move the input to the left of labels and flip order of the button at the bottom of the block

Update Diverse Poll Block css

---

sites/ccnewsnow.com/config/navigation.js
sites/diverseeducation.com/config/navigation.js
sites/diversemilitary.net/config/navigation.js
sites/divhealth.net/config/navigation.js

This link is currently broke on Diverse's end, needs to be moved over to different server per Ralph

Comment out keep it real link until fixed

---

sites/diverseeducation.com/server/templates/index.marko

Restore poll to home page with 300x250

---

sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/server/routes/index.js
sites/diverseeducation.com/server/routes/subscribe.js
sites/diverseeducation.com/server/styles/index.scss
sites/diverseeducation.com/server/templates/subscribe.marko

Add subscribe landing page for DE

---

packages/global/scss/_variables.scss
sites/ccnewsnow.com/config/site.js
sites/diverseeducation.com/config/site.js
sites/diversemilitary.net/config/site.js
sites/divhealth.net/config/site.js

Change Nav bar logo height from 45px to 60px

---

packages/global/components/blocks/marko.json
packages/global/components/blocks/section-feed.marko
packages/global/components/layouts/website-section/feed.marko
packages/global/components/layouts/website-section/marko.json
packages/global/scss/components/_podcasts-page.scss
packages/global/scss/core.scss
sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/config/site.js
sites/diverseeducation.com/server/components/blocks/promo-card-rotation.marko
sites/diverseeducation.com/server/routes/website-section.js
sites/diverseeducation.com/server/templates/website-section/podcasts.marko

Add podcasts layout, promo block

---

sites/diverseeducation.com/config/navigation.js

Update Diverse nav items

---

packages/global/components/blocks/featured-jobs.marko
packages/global/components/blocks/marko.json
packages/global/scss/components/_page-wrapper.scss
packages/global/scss/components/blocks/_featured-jobs.scss
sites/diverseeducation.com/server/templates/content/index.marko

New featured jobs block

---

packages/global/components/blocks/featured-jobs.marko
packages/global/components/layouts/website-section/feed.marko
packages/global/scss/components/blocks/_esurveypro.scss
sites/diverseeducation.com/server/templates/index.marko
sites/diverseeducation.com/server/templates/subscribe.marko
sites/diverseeducation.com/server/templates/website-section/index.marko

Update layout to include new jobs block

---

sites/diverseeducation.com/config/navigation.js

Change Awards/Honors to Top 100 primary nav DE.

---

packages/global/scss/components/_site-navbar2.scss
sites/diverseeducation.com/config/site.js

Update diverse education logo

---

packages/global/components/magazine/blocks/magazine-issues.marko
packages/global/components/magazine/blocks/marko.json
packages/global/scss/components/blocks/_magazine-issues.scss
packages/global/scss/core.scss

https://trello.com/c/jcyZgGDy/5-logo-option-for-featured-jobs-block

Create new magazine issue block with 4 cover images & subscribe/archive links

---

packages/global/components/layouts/content/default.marko

Update sidebar logic to use filter instead of for loop.

---

sites/diverseeducation.com/config/navigation.js

Add ‘Shop’ to navigation, menu & footer

---

sites/diverseeducation.com/server/routes/website-section.js
sites/diverseeducation.com/server/styles/components/awards.scss
sites/diverseeducation.com/server/styles/components/awards/_john-franklin.scss
sites/diverseeducation.com/server/templates/website-section/john-hope-franklin.marko

- Add route
- Add Static version for now(website-schedueld-content version commented out in file)
- Make award specific css file.

Add the John Hope Franklin awards page

---

sites/diverseeducation.com/config/navigation.js

Add Webinars to menu and footer under Resources

---

sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/server/templates/website-section/john-hope-franklin.marko

- move register button
- fix e in Kimberle
- add pagination controls and ad to bottom of page.

Update the layout of the John Hope Franklin landing page

---

sites/diverseeducation.com/config/navigation.js

Change ‘Webinars’ to ‘Webcasts’ in menu

---

packages/global/browser/index.js
packages/global/components/site-menu/components/search.marko
packages/global/package.json
packages/global/templates/search.marko
sites/ccnewsnow.com/config/site.js
sites/diverseeducation.com/config/site.js
sites/diversemilitary.net/config/site.js
sites/divhealth.net/config/site.js

Implement google site search

---

packages/global/browser/index.js
packages/global/components/layouts/website-section/podcast-feed.marko
packages/global/package.json
packages/global/scss/core.scss
packages/global/start-server.js
sites/diverseeducation.com/config/contact-us.js
sites/diverseeducation.com/config/site.js
yarn.lock

Add contact us form to Podcast landing page.

---

sites/ccnewsnow.com/config/navigation.js
sites/diverseeducation.com/config/navigation.js
sites/diversemilitary.net/config/navigation.js
sites/divhealth.net/config/navigation.js

Add About Us to menu(s) and footer(s).

---

packages/global/components/layouts/website-section/podcast-feed.marko
sites/diverseeducation.com/config/site.js

Add wufoo form support to  podcast page

---

sites/diverseeducation.com/server/templates/index.marko

**The group went with layout B**

Update Divers Education's home page layout

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Add nominate now button to arthur ashe page

---

sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/server/routes/awards/emerging-scholars.js

Update merging scholars to 2022

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Allow html styling tags to description & add deadline under button

---

packages/global/components/layouts/content/default.marko
packages/global/scss/components/_on-the-move-page.scss

On The Move image wrapping correction.

---

packages/global/components/layouts/content/default.marko
packages/global/components/layouts/content/product.marko
packages/global/components/layouts/content/whitepaper.marko
packages/global/scss/core.scss
packages/theme-monorail/components/nodes/author-published.marko
packages/theme-monorail/components/nodes/content-published.marko

Remove updated date on content pages.

---

packages/global/components/layouts/content/default.marko
packages/global/graphql/fragments/content-page.js
packages/global/package.json
packages/theme-monorail/components/identity-x/content-page-gate.marko
packages/theme-monorail/components/identity-x/marko.json
packages/theme-monorail/graphql/fragments/content-page.js
packages/theme-monorail/package.json
packages/theme-monorail/utils/get-content-preview.js
yarn.lock

- Add content-preview-helper to monorail theme
- Add idx content-page-gate component
- Update userRegistration to use isCurrentlyRequired vs isRequired
- Add gating css
- update @parameter1/base-cms deps to 2.71.0

Add IdentityX content gating components

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Update the deadline for arthur ashe nomination

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/champions.marko

Update deadline section on diverse champions

---

sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/server/routes/awards.js
sites/diverseeducation.com/server/routes/awards/graduate-scholars.js
sites/diverseeducation.com/server/routes/awards/redirects.js
sites/diverseeducation.com/server/styles/components/awards.scss
sites/diverseeducation.com/server/styles/components/awards/_graduate-scholars.scss
sites/diverseeducation.com/server/templates/website-section/awards-honors/graduate-scholars/index.marko

Create Graduate Scholars landing page

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/champions.marko

Change his to her on diverse champions page-DE

---

packages/global/components/site-header-2.marko
sites/ccnewsnow.com/config/navigation.js

Showing changed version:
Showing that it will not "break" the other sites with only 1 button up here.

Add Post A Job Button to header CCN.

---

sites/diverseeducation.com/server/templates/static-pages/configs/mppwsa.js
sites/diverseeducation.com/server/templates/static-pages/configs/mppwsa/profiles.js
sites/diverseeducation.com/server/templates/static-pages/mppwsa.marko

Add button for previous year's content on MPPWSA

---

sites/diverseeducation.com/config/navigation.js

Add ‘Graduate Scholars’ to hamburger menu (Diverse)

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Remove nominate now button and deadline on Arthur Ashe page

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Add ‘Roster’ button to arthur-ashe page

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Update ‘roster’ button link to secure address

---

sites/divhealth.net/server/templates/index.marko

Use same 'Featured Jobs' block as DE and rearrange other news block to fill 'blank'

---

sites/ccnewsnow.com/server/templates/index.marko
sites/diversemilitary.net/server/templates/index.marko

same block on  Diverse Education
DIVERSE MILITARY:
CCNEWS NOW:

Adjust ‘Featured Jobs’ block to be consistent with

---

packages/global/scss/_variables.scss
packages/global/scss/components/_on-the-move-page.scss
packages/global/scss/components/_podcasts-page.scss
packages/global/scss/core.scss

Instructions for how to get StyleLint working again can be found in the Parameter1 Trello board on the card "Review/fix stylelint configs for website/newsletter repos"

Stylelint corrections

---

packages/global/components/layouts/website-section/podcast-feed.marko
packages/global/scss/components/_podcasts-page.scss

Desktop:
iPad Mini:
iPhone SE:

Add video embed for "latest episode" in right rail, podcast section page

---

sites/diverseeducation.com/config/navigation.js

I added the link to the "Editorial Calendar" on the hamburger menu.

add dynamic editorial calendar to navigation

---

sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/server/routes/awards.js
sites/diverseeducation.com/server/routes/awards/top-women.js
sites/diverseeducation.com/server/templates/static-pages/mppwsa-yearly.marko
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-all.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2012.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2013.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2014.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2015.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2016.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2017.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2018.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2019.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2020.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2021.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/config/top-women-yearly/2022.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/index.marko

Create 'Top Women' page

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/emerging-scholars/index.marko

Please upload changes asap,  thanks!

add nominations button to Emerging Scholars page

---

sites/diverseeducation.com/config/navigation.js

Changed shop url to shop.diverseeducation.com

updated shop url

---

sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

This change must be made tomorrow at 2 p.m.

update emerging scholars url on menu

---

sites/diverseeducation.com/server/routes/awards/emerging-scholars.js

update route on emergeging scholars landing page

---

sites/diverseeducation.com/server/styles/index.scss

Allow scroll when menu is open

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Remove ‘Nominate Now’ button from arthur ashe page

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Adjust year call to pull in 2023 vs 2033

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/champions.marko

Updated Diverse Champions Winner.

Update on Diverse Champions page

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Add 2 ad units to Arthur Ashe landing page

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Change ‘rotation’ to ‘rail’ for ad placements

---

packages/global/scss/core.scss

https://github.com/parameter1/cox-matthews-associates-websites/pull/228

Adjust breadcrumbs and magazine css

---

sites/diverseeducation.com/server/templates/static-pages/configs/mppwcc-yearly/2023.js
sites/diverseeducation.com/server/templates/static-pages/mppwcc-yearly.marko

Correct MPPWCC 2023 data and display of `tableSeven`

---

packages/global/scss/core.scss

This is for the cards below the hero incase they load at that res

ensure card css is critical on home with

---

packages/global/config/identity-x.js

Remove list of hidden profile fields

---

sites/ccnewsnow.com/config/identity-x.js
sites/diverseeducation.com/config/identity-x.js
sites/diversemilitary.net/config/identity-x.js
sites/divhealth.net/config/identity-x.js

Add newsletter product configuration per brand on profile page

---

sites/diverseeducation.com/config/identity-x-opt-in-hooks.js
sites/diverseeducation.com/config/identity-x.js

Update productID (nl auto signup) & add id for custom field, Diverse Education Profile form

---

sites/diverseeducation.com/config/site.js

Update header logo--STAGING

---

packages/global/components/site-header-2.marko

Conditionally show the user icon button in the upper right nav when enabled.  Depending on the user state it will link to /user/login or /user/profile

Add login/profile button to upper right navigation

---

sites/diverseeducation.com/config/identity-x.js

Send idX’s categories QA with user data to GTM/GA4

---

sites/diverseeducation.com/config/navigation.js

Set menu links to subsections over sites

---

sites/diverseeducation.com/config/site.js

Replace logo URL with new version for staging

---

sites/diverseeducation.com/config/site.js

Replace footer logo URL for staging, Diverse Education

---

sites/diverseeducation.com/config/site.js

Update Logo URLs, Diverse Education

---

packages/global/scss/components/blocks/_esurveypro.scss
sites/diverseeducation.com/server/styles/index.scss

Update primary color & survey button color

---

sites/diverseeducation.com/server/styles/index.scss

Remove secondary (‘About’) header from dropdown menu

---

packages/global/scss/components/_doit-page.scss
packages/global/scss/core.scss
sites/diverseeducation.com/config/navigation.js

Reduce size of DOIT page logo

---

packages/global/scss/components/_doit-page.scss

Reduce DOIT logo and include mobile sizing

---

packages/global/scss/core.scss

ensure page-rail node-list__header styles match

---

packages/global/components/blocks/greeting-video.marko
packages/global/components/blocks/marko.json
packages/global/components/layouts/content/company.marko
packages/global/components/layouts/content/default.marko
packages/global/components/layouts/content/product.marko
packages/global/components/layouts/content/whitepaper.marko
packages/global/components/layouts/website-section/cards.marko
packages/global/components/layouts/website-section/feed.marko
packages/global/components/layouts/website-section/home.marko
packages/global/components/layouts/website-section/podcast-feed.marko
packages/global/components/layouts/website-section/products.marko
packages/global/components/layouts/website-section/upcoming-archive-feed.marko
packages/global/templates/content/contact.marko
packages/global/templates/dynamic-page/index.marko

Also setup video to be muted with auto play enabled

Create and use greeting video block

---

packages/global/scss/components/_doit-page.scss

Remove margin-left over medium breakpoint, DOIT page

---

packages/global/components/blocks/greeting-video.marko

Add rel=0 to youtube url to hide video suggestions at the end of clip

---

packages/global/components/blocks/greeting-video.marko

Remove incorrect ‘?’ from url

---

sites/diverseeducation.com/config/site.js
sites/diverseeducation.com/server/styles/index.scss

Change header and footer to 40th logo

---

packages/global/templates/content/components/presented-by.marko
sites/diverseeducation.com/server/components/blocks/promo-card-rotation.marko

Native-X Story "eyebrow" adjustments

---

packages/global/components/layouts/website-section/podcast-feed.marko
sites/diverseeducation.com/config/site.js

Podcast "Listen Here" block

---

sites/diverseeducation.com/server/components/blocks/arthur-ashe-award-content.marko

Re-order columns of Arthur Ashe Awards

---

sites/diverseeducation.com/server/components/blocks/arthur-ashe-award-content.marko

Correct to Male Winner and Female Winner respectively

---

sites/diverseeducation.com/config/identity-x.js

Add custom questions to profile form

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/emerging-scholars/index.marko
sites/diverseeducation.com/server/templates/website-section/awards-honors/graduate-scholars/index.marko

Remove year from breadcrumbs, Rising Graduate and Emerging Scholar landing pages

---

sites/diverseeducation.com/server/styles/components/awards.scss
sites/diverseeducation.com/server/templates/static-pages/mppwcc-yearly.marko
sites/diverseeducation.com/server/templates/static-pages/mppwsa-yearly.marko
sites/diverseeducation.com/server/templates/website-section/awards-honors/top-women/index.marko

Dropdown on MPPWCC, MPPWSA, Top Women for Other Years portion of page

---

packages/global/scss/components/blocks/_esurveypro.scss

Not sure if this actually makes a difference, or how else to test the changes since they don't display 'incorrect' anymore on dev tools.

eSurvey inline radio and answer styling adjustment

---

sites/diverseeducation.com/server/components/blocks/latest-podcast.marko

Additional styling adjustment for Video version of Podcast block

---

sites/diverseeducation.com/config/i18n.js
sites/diverseeducation.com/index.js

Add and utilize i18n to change title of Most Popular block

---

packages/global/scss/components/_ads.scss

Remove Sponsored text above suggested video on article pages

---

sites/diverseeducation.com/config/site.js

Revert to original site logo

---

sites/diverseeducation.com/config/site.js
sites/diverseeducation.com/server/styles/index.scss

Increase footer logo height to 60px

---

sites/diverseeducation.com/server/components/blocks/arthur-ashe-award-content.marko

Update section name for arthur ashe award

---

sites/diverseeducation.com/server/styles/components/awards.scss
sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Add componentry and styles for Arthur Ashe year dropdowns

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Move buttons around on Arthur Ashe blocks

---

sites/diverseeducation.com/server/templates/static-pages/configs/mppwcc-yearly/2025.js
sites/diverseeducation.com/server/templates/static-pages/mppwcc-yearly.marko

Flip table 3 & 4 on MPPWCC

---

sites/diverseeducation.com/server/templates/static-pages/mppwsa-yearly.marko

Change Other to Previous on MPPWSA template

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
.github/workflows/integration-tests.yml
sites/diverseeducation.com/server/templates/website-section/awards-honors/graduate-scholars/index.marko
sites/diversemilitary.net/package.json
sites/divhealth.net/package.json

Remove button from Graduate Scholars

---

sites/diverseeducation.com/server/templates/website-section/awards-honors/arthur-ashe/index.marko

Appropriately filter Sport Winners to after 2015, Arthur Ashe

---

sites/diverseeducation.com/config/site.js
sites/diverseeducation.com/server/styles/index.scss

Use logo with tagline and increase size

---

packages/global/components/blocks/esurveypro.marko
sites/diverseeducation.com/config/navigation.js
sites/diverseeducation.com/config/newsletter.js
sites/diverseeducation.com/config/site.js
sites/diverseeducation.com/server/styles/index.scss
sites/diverseeducation.com/server/templates/static-pages/diverse-poll.marko

Rebranding updates, name changes

---

sites/diverseeducation.com/config/navigation.js

Remove DOIT and change Diverse Champions to Champions Awards
